version: 0.0
os: linux
files:
  - source: student.war
    destination: /usr/local/apache-tomcat-8.5.50/webapps
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300

